(package "chatgpt-sideline"
         "0.1.0"
         "Sideline support for chatgpt")

(website-url "https://github.com/emacs-openai/chatgpt-sideline")
(keywords "convenience" "chatgpt" "ai")

(package-file "chatgpt-sideline.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'jcs-elpa)
(source 'gnu)
(source 'melpa)

(depends-on "emacs" "27.1")
(depends-on "chatgpt")
(depends-on "sideline")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
